name: Sync Routes as Submodule

on:
  push:
    branches:
      - main

jobs:
  sync-routes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: 'redgreat/me'
        token: ${{ secrets.ME_PAT }}
        path: 'me'

    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: 'redgreat/racewong'
        token: ${{ secrets.ME_PAT }}
        path: 'racewong'

    - name: Add routes as submodule
      run: |
        cd me
        git config --global user.name 'racewong'
        git config --global user.email 'rubygreat@msn.com'
        git submodule add -b main -f routes pages/routes
        git commit -m "Add routes as submodule"
        git push origin main

    - name: Synchronize submodule
      run: |
        cd me
        git submodule update --remote --merge
        git commit -m "Synchronize routes submodule"
        git push origin main
