name: PushRoutes

on:
  push:
    branches:
      - main

jobs:
  push_routes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Add compiled files to git
        run: |
          if [ -d "./routes" ]; then
            git add ./routes
          else
            echo "Output directory does not exist."
            exit 1
          fi

      - name: Push Routes
        env:
          ACCESS_TOKEN: ${{ secrets.ME_PAT }}
        run: |
          git remote add origin https://github.com/redgreat/me.git
          
          if git diff --cached --quiet; then
            echo "无新文件提交"
          else
            git config --global user.name 'racewang.action'
            git config --global user.email 'rubygreat@msn.com'
            git commit -m "自动提交轨迹文件"
            git push origin HEAD:main --force
          fi
